### ISSUE TITLE
Publish on packagist

### ISSUE THREAD

**Issue by arnegroskurth** [p1ho/accessibility-checker#1]
Is there a particular reason, why you do not want to publish the package on packagist?

Having to add the github-repo manually just clutters the the composer.json unnecessarily.

**Comment by arnegroskurth** [comment]
@p1ho And thanks for the work!

**Comment by p1ho** [comment]
@arnegroskurth Thanks for using this project! I hadn't put it out because I felt some features might still be incomplete (for example, the color contrast checker [makes several assumptions](https://github.com/p1ho/accessibility-checker/blob/master/src/ColorContrast/Checker.php#L14) and does not work well with heavily themed Wordpress pages from my own testing)

I can try to publish it when I'm free, and I'll ping you here.

Feel free to open other issues for bugs!

**Comment by arnegroskurth** [comment]
@p1ho You could still publish the package e.g. as version 0.1.0 which would still allow breaking changes of the package API before the 1.0.0 release (see: https://semver.org/)

However, if the API is already stable and those bugs are fixable without having to change the API then you could already release it as 1.0.0

**Comment by p1ho** [comment]
Thanks for the suggestion! I think I'll release as version 0.1.0 since the output format may be improved (and would cause breaking changes if we make improvements). If it sees more use in the future and people are fine with the output format, then I can release the 1.0.0 version.

**Comment by p1ho** [comment]
@arnegroskurth [Published](https://packagist.org/packages/p1ho/accessibility-checker)! Please try it out and let me know if there are issues.

**Comment by arnegroskurth** [comment]
Thanks!
